package com.minibank.gateway.filter;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * Generates HMAC-SHA256 based internal auth tokens for service-to-service communication.
 *
 * <p>Tokens are generated by the API Gateway and attached to downstream requests
 * via the {@code X-Internal-Token} header. Downstream services validate these tokens
 * using {@code InternalAuthFilter} to prevent unauthorized direct access (gateway bypass).</p>
 *
 * <p>Token format: Base64Url(timestamp:hmac(timestamp:requestPath))</p>
 *
 * <p>TTL: 5 minutes (configurable via {@code internal.auth.token-ttl}).</p>
 */
@Slf4j
@Component
public class InternalTokenGenerator {

    @Value("${internal.auth.secret}")
    private String internalSecret;

    @Value("${internal.auth.token-ttl:300000}")
    private long tokenTtl;

    /**
     * Generates an internal auth token for the given request path.
     *
     * @param requestPath the downstream request path
     * @return Base64Url-encoded token string
     */
    public String generateToken(String requestPath) {
        long timestamp = System.currentTimeMillis();
        String data = timestamp + ":" + requestPath;
        String hmac = calculateHmac(data);
        String rawToken = timestamp + ":" + hmac;
        log.debug("Generated internal token for path: {}", requestPath);
        return Base64.getUrlEncoder().withoutPadding()
                .encodeToString(rawToken.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Calculates HMAC-SHA256 for the given data using the internal secret.
     */
    private String calculateHmac(String data) {
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            SecretKeySpec secretKey = new SecretKeySpec(
                    internalSecret.getBytes(StandardCharsets.UTF_8), "HmacSHA256");
            mac.init(secretKey);
            byte[] hmacBytes = mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
            return Base64.getUrlEncoder().withoutPadding().encodeToString(hmacBytes);
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate HMAC for internal token", e);
        }
    }
}
